site_name: My Second Brain
theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
nav:
  - Home: index.md
  - MkDocs: mkdocs/mkdocs.md
  - Git: git/git.md
  - Build Tools:
      - Build Tools: build-tools/build-tools.md
      - Maven: build-tools/maven.md
      - Gradle: build-tools/gradle.md
