site_name: My Second Brain
theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
nav:
  - Home: index.md
  - Automation:
      - Allure Lifecycle: automation/allure-lifecycle.md
      - Cucumber + JUnit 5: automation/cucumber-junit5.md
  - TDM:
      - Architecture: tdm/architecture.md
