site_name: My Second Brain
theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
nav:
  - Home: index.md
  - MkDocs: mkdocs/mkdocs.md
  - Build Tools:
      - Maven: build-tools/maven.md
